### PR TITLE
use HTTPS for downloading sources (2nd try)

### PR DESCRIPTION
**Pull request by i-work-at-ait**
## Proposed changes

please use HTTPS for downloading sources (e.g. `curl`, `wget`).

## Types of changes

What types of changes does your code introduce to the project:

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

-   [x] I have read the [CONTRIBUTING](https://github.com/FIWARE/context.Orion-LD/blob/master/CONTRIBUTING.md) doc
-   [x] I have signed the [CLA](https://fiware.github.io/contribution-requirements/individual-cla.pdf)
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by i-work-at-ait** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by kzangeli — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by kzangeli** [comment]
It worked! :)

**Comment by i-work-at-ait** [comment]
yeah it worked :)
using the `noreply` address provided by GitHub instead of a non-existing/fake address helps a lot in such cases ;)

**Pull request merged**
