### PR TITLE
Fix json syntax on documentation

### PR DESCRIPTION
**Pull request by pedrxd**
## Proposed changes

There is a typo error on some json on the documentation.

## Types of changes

-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

-   [x] I have read the [CONTRIBUTING](https://github.com/FIWARE/context.Orion-LD/blob/master/CONTRIBUTING.md) doc
-   [x] I have signed the [CLA](https://fiware.github.io/contribution-requirements/individual-cla.pdf)
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by kzangeli — APPROVED** [review]
Great, thanks!!

LGTM

**Comment by kzangeli** [comment]
Pedro, it seems we have a problem with the CLA ...
Dice que no tienes cuenta en github. Sin eso no te deja firmar el CLA ...

**Comment by pedrxd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pedrxd** [comment]
El commit tenia un correo equivocado, ya está corregido.

**Comment by kzangeli** [comment]
> El commit tenia un correo equivocado, ya está corregido.

Genial, gracias!

**Comment by kzangeli** [comment]
The functest error is a timing issue.
I'll fix it using (#SORT_START and #SORT_END in the functest)

**Pull request merged**
