### PR TITLE
Fix 1393

### PR DESCRIPTION
**Pull request by aquarta**
## Proposed changes

Fix missing previous values for upsert/option=update call (https://github.com/FIWARE/context.Orion-LD/issues/1393)

## Types of changes

added previousValues(inEntityP, dbAttrsP); calls in  src/lib/orionld/serviceRoutines/orionldPostBatchUpsert.cpp
added a functional test

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

-   [ ] I have read the [CONTRIBUTING](https://github.com/FIWARE/context.Orion-LD/blob/master/CONTRIBUTING.md) doc
-   [ ] I have signed the [CLA](https://fiware.github.io/contribution-requirements/individual-cla.pdf)
-   [X] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sgheppy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aquarta** [comment]
I think I made a mistake with commits, I will resolve this as soon as possibile


This pr is needed since the IOTagent use upsert to send measures, and this prevent to use the previosValue filed in subscription/notification when using LD

**Comment by aquarta** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kzangeli** [comment]
Hello there and thank you so much for contributing.
The feature "showChanges" in notifications was only partially implemented and this PR adds a little to it, so, that is very welcome!
However, I see a few of my changes in the diff - it seems you need to merge in the latest from the develop branch.

Apart from that, yesterday I noticed a problem with the docker files, a dependency package has disappeared and the build fails accordingly.
So, once this really runs, it will most probably fail, no need to worry.
A fix is on its way, a radical modification of the docker files.  Hopefully today.

**Comment by kzangeli** [comment]
The dockerfile problem has been solved.
I have two queued PRs I need to merge, now that I can.
After that, if this PR is still "as is", I'll use the github button to merge what's in develop.

**Review by kzangeli — APPROVED** [review]
Thank you for the contribution, very much appreciated!

**Comment by kzangeli** [comment]
(I fixed a few very minor style-guide related issues to make the PR pass the compliance tests)

**Pull request merged**
