### PR TITLE
use HTTPS for downloading sources

### PR DESCRIPTION
**Pull request by i-work-at-ait**
## Proposed changes

use HTTPS for downloading sources (e.g. with `wget`).

## Types of changes

What types of changes does your code introduce to the project: 

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

-   [x] I have read the [CONTRIBUTING](https://github.com/FIWARE/context.Orion-LD/blob/master/CONTRIBUTING.md) doc
-   [x] I have signed the [CLA](https://fiware.github.io/contribution-requirements/individual-cla.pdf)
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kzangeli** [comment]
The checks fail as the CLA isn't signed.
Could you fix that, please?
Just follow the instructions.

Sorry about that, and thanks for the contribution!!!

**Comment by i-work-at-ait** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kzangeli** [comment]
github is still not convinced. the CLA thing still fails:

> user seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub
> account, please add the email address used for this commit to your account.

Could you take a look, please?

**Comment by i-work-at-ait** [comment]
i am sorry for the inconvenience.

this is probably due to the fact that i have enabled "keep my email addresses private" but haven't set the `...@users.noreply.github.com` address in my `.gitconfig` but a generic/non-existing `user@example.com` instead.
hence, the PR is linked to that non-existing email address, which obviously isn't linked to a GitHub account.
i have since fixed that issue (i.e. i have set the `noreply` address in my `.gitconfig`).

honestly, i have no idea on how to fix this besides opening a new PR and closing this one.
but i am open for any suggestions.

again, i am sorry for this inconvenience.

**Comment by kzangeli** [comment]
Hey, not really your fault.
We've just put some special restrictions for PRs.
I'm thankful for your contribution and this little mishap, I'm sure we'll fix it somehow.
If you think a close and reopen of the PR might fix the problem, let's try that.
And if that doesn't work, we'll try something different

**Pull request closed without merging**
