### PR TITLE
fix issue-559

### PR DESCRIPTION
**Pull request by manaty226**
Metadata should be replaced if `actionType` is `NGSI_MD_ACTIONTYPE_UPDATE`.
The conventional updating way is applied for `NGSI_MD_ACTIONTYPE_APPEND`.

Reason:
In the conventional way, if `targetAttr` has no metadata, an entity's metadata was not changed because of 
`for (unsigned int jx = 0; jx < targetAttr->metadataVector.size(); jx++) {...}`.
Thus, I add another update processing if `NGSI_MD_ACTIONTYPE_UPDATE`.

### CODE REVIEW

**Comment by kzangeli** [comment]
This is great, thanks again, @manaty226 .
A known bug that really needed fixing!
I'd like to wait a little with the merge though.
It modifies crucial code inside mongoBackend, possibly affecting lots of functionality of the broker.
So, I'd like to see a full run of the func test suite but as "github actions" is currently under construction and no tests are run, we have a problem there.
A fix is on the way, so once ready, we'll merge it into this PR and we'll get the tests executed.
I'm talking to my DevOps guy about this. Hope to have it fixed soon.

Another option, @manaty226  is that you swear that you've run the entire test suite (make test) - both unit tests and functional tests and not seeing any error. With that done, we could merge immediately.

Actually, a "make valgrind" would be nice as well - to ensure there aren't any memleaks nor other errors (that run typically takes 5-6 hours - I normally start it just before the end of the work day to check the result the day after)

**Comment by manaty226** [comment]
OK. I'll wait to merge the code until fixing the tests.
My PR has passed the unit test (without `MongoDbUpdateFail`) and the func. tests with "-ld" option 
but executing "make valgrind" may be too large to run on my laptop.
Thank you for your support!

**Comment by kzangeli** [comment]
ok, that might be good enough.
The valgrind test suite I run locally every now and then, especially when preparing a new release.
Just run the entire suite (not only the NGSI-LD tests), as the modified part is used also by NGSIv2.
If that works, we're golden - it should take about 90 min, not much more.

What do you mean without MongoDbUpdateFail?
Is it that error I found recently and created an issue about?
If so, all OK (and let me know when the func test suite finishes and I'll merge)

**Comment by manaty226** [comment]
OK. I will run all functional tests now.
You are right that "without MongoDbUpdateFail" means about the issue you created.

**Comment by manaty226** [comment]
All functional tests have done but some tests failed as bellow.
I believe that the no. 1156 test should be fixed about an expected notification data as same as "ngsild_patch_entity_attr_with_subscription.test".
Also, maybe the no. 2015 test is broken (only Content-Length is different between .out and .regexpect).

I will check the other tests about why those failed.

```
----------- Failing tests ------------------
  o  0000_ipv6_support/ipv4_ipv6_both.test
  o  0000_ngsild/ngsild_subscription_with_mqtt_notification_01.test
  o  0706_direct_https_notifications/direct_https_notifications.test
  o  0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test
  o  1156_mq_as_uri_param_for_metadata/q_and_mq_as_uri_param_for_metadata.test
  o  2015_notification_templates/notification_templates_cache_refresh.test
```

**Comment by manaty226** [comment]
@kzangeli after all, my PR has passed all tests except for the below test cases. 
"2015_notification_..." should be fixed because one of the actual Content-Length has been different from regexpect.  
Thus, I'll post another PR to fix "2015_notification_...".
Are "0706..." tests also broken? The tests always fail reported in "Installation Guide for the Orion-LD Functional Test Suite" 

```
----------- Failing tests ------------------
  o  0706_direct_https_notifications/direct_https_notifications.test
  o  0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test
  o  2015_notification_templates/notification_templates_cache_refresh.test
```

**Comment by kzangeli** [comment]
Hi again, ok, that  sounds good.
Those threeare known failure, I exclude them from the test suite by setting the `CB_SKIP_FUNC_TESTS` env var:
```
CB_SKIP_FUNC_TESTS='0706_direct_https_notifications/direct_https_notifications.test 0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test 2015_notification_templates/notification_templates_cache_refresh.test'
```

So, I believe we're ready for the merge then, except for one detail - I keep the changes in the file  CHANGES_NEXT_RELEASE.
Add a line in there about the bug you fixed, including the issue number - you'll see how it works.

**Comment by manaty226** [comment]
I understand and added a line of this fixing in CHANGE_NEXT_RELEASE. 
Thank you!

**Comment by kzangeli** [comment]
Great!

**Pull request merged**
