### PR TITLE
Update URL for context file

### PR DESCRIPTION
**Pull request by fisuda**
## Proposed changes

This PR updates URL for context file in functionalTest. I'm putting a context file at context.lab.letsfiware.jp. For stability, I'd like to change a URL of context file. I put same context file at new URL.  It would be great if you could review this PR.

Thanks!

## Types of changes

What types of changes does your code introduce to the project: _Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

-   [X] I have read the [CONTRIBUTING](https://github.com/FIWARE/context.Orion-LD/blob/master/CONTRIBUTING.md) doc
-   [X] I have signed the [CLA](https://fiware.github.io/contribution-requirements/individual-cla.pdf)
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

N/A

### CODE REVIEW

**Comment by fisuda** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by kzangeli — APPROVED** [review]
LGTM

**Comment by kzangeli** [comment]
I have no clue why the tests aren't executed ...
The PR is GOOD, I'd just like to see the tests finish successfullt before I merge it

**Comment by kzangeli** [comment]
What if you add an empty commit to re-trigger the github actions?
I don't have the buttons here so I can't do it myself ...

No need, found an easy way - editing one of the files right here on github

**Comment by fisuda** [comment]
I received the following message:
```
First-time contributors need a maintainer to approve running workflows
```

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

image

**Comment by kzangeli** [comment]
The thing is, I did approve it. Yesterday.
I hoped that would do the trick.
Seeing that it didn't, I hoped a new commit pushed to it would do the trick - that also didn't work :(
I'll try to get help ...

**Comment by kzangeli** [comment]
So, I asked for help and our github expert tells me the following:

_The problem is that the commiter (fisuda) manually disabled the tests in his repo. He needs to enable the test workflows again so that they can run a report there._

So, assuming he is right (he almost always is), can you try that?

**Comment by fisuda** [comment]
Thank you for your help.

I sent a new PR #1027 that was created at another repository of another account.

I checked my actions in my repo. They were actions of telefonica/fiware-orion repo. It seems that the actions cannot start because I created this PR from the clone of telefonicaid/fiware-orion. But, I have already a clone of telefonicaid/fiware-orion repo so that I cannot create a clone of the FIWARE/context.Orion-LD repo. For this reason, I created a clone with another account and created another PR from it.

We can close this PR. Let's move on to the PR #1027

Thanks.

image

**Comment by kzangeli** [comment]
This didn't work (github actions won't start).
Trying again in a new PR (#1027 )

**Pull request closed without merging**
