### PR TITLE
Use pkg-config to find libraries and include files

### PR DESCRIPTION
**Pull request by rschwebel**
Currently, the CMakeLists.txt files open-code how to find header files and libraries. As we have pkg-config as a mechanism to find these files in a generic way, it should be possible to get rid of most of the ifdeffery and thus the differentiation for all those different distributions. 

In addition, pkg-config takes care of things like sysroot (when not building natively but in a cross enviroment). 

It also makes it possible to get rid of the fact that orion-ld currently makes the arbitrary assumption that some components are built into /usr/local, which might not be the case. With pkg-config, it doesn't matter if those other packages are installed into /usr or /usr/local or elsewhere, as long as they have been properly installed and pkg-config can actually find them.

Note that I havn't been able to test these changes on all the different distributions, so a closer look might be necessary if it really works there.

### CODE REVIEW

**Comment by rschwebel** [comment]
The mintaka test seems not to find libmongoc-1.0.pc. Strange, as https://github.com/mongodb/mongo-c-driver/tree/master/src/libmongoc/src clearly shows that it is being installed.

Are you sure mongo-c-driver is properly installed on the test system, with the usual "make install"?

[Edit:] The 1.25.0 release removes libmongoc-1.0.pc (I tested with an earlier version), and I don't know why. Asked here:
https://github.com/mongodb/mongo-c-driver/pull/1301 but they have probably removed support for non-ssl. Adapting the patches...

**Comment by rschwebel** [comment]
Ok, now libmongoc-ssl-1.0 is not installed...

**Comment by rschwebel** [comment]
Ok, the recent 1.25.0 release of mongo-c-driver made things more complicated. Need to port to that version and find out how things are meant to be used there. I'm marking this PR as "draft" for the moment.

**Comment by rschwebel** [comment]
Ok, I tested with mongo-c-driver-1.25.0 now, and while removing libmongoc-1.0.pc.in from the source, it properly generates a libmongoc-1.0.pc file and pkg-config works as expected. So something must be wrong in your CI setup.

**Comment by rschwebel** [comment]
I found the pc files for some of the depencencies in non-standard locations, currently libmongo-client.pc is still missing. I continue investigating ...

**Comment by rschwebel** [comment]
Ok, libmongo-client comes from that same old rotten mongo-cxx-driver that has been deprecated back in 2016. It really is a lost case. I leave that one as it is.

**Comment by kzangeli** [comment]
Hello there, and thank you for the contribution!

I'm perfectly fine with this type of changes.
Can't say I care too much, as it's just a thing you write once and kind of forget about.

One important thing though, very few people compile their own broker, but, afaik. those that do use Ubuntu.
So, this MUST work with Ubuntu 18.04, 20.04, and 22.04.
And, of course, in github actions.

As long as you can guarantee those four working, I'm perfectly fine with the suggested changes.

**Comment by rschwebel** [comment]
Hi Ken,

> I'm perfectly fine with this type of changes. Can't say I care too much, as it's just a thing you write once
> and kind of forget about.

That's how the build system code looks like ;-)

> One important thing though, very few people compile their own broker, but, afaik. those that do use
> Ubuntu. So, this MUST work with Ubuntu 18.04, 20.04, and 22.04. And, of course, in github actions.
> 
> As long as you can guarantee those four working, I'm perfectly fine with the suggested changes.

Thanks for that valuable information, will test those platforms in more detail once I'm finished with the outstanding issues.

**Comment by kzangeli** [comment]
This PR is getting stale.
To be discarded in the next few weeks, unless it is updated to AT LEAST WORK in github actions.

**Comment by rschwebel** [comment]
Thanks for the heads-up, I have rebased the patches to the develop branch and will look at the ci fallout.

**Comment by rschwebel** [comment]
The unit tests are fixed now: The PKG_CONFIG_PATH had to be extended with /usr/local/lib/pkgconfig (due to the unusual installation mechanism for libs in /usr/local - the whole library installation in the CI setup is a mess). Additionally, in the last patch series I missed adding the pkg-config derived ${LIBMICROHTTPD_LIBRARIES} to the unitTest.

With these fixed, the "Deploy Baseimage" is now the last check that fails. I'll have a look.

**Comment by rschwebel** [comment]
The failing "Deploy Baseimage / deploy-quay" checks fail because I don't have the permissions to push there. Seems like there is nothing I can do against this.

Ken, I think this patch series is ready now, I'll undraft it. Please have a look.

**Comment by kzangeli** [comment]
> The failing "Deploy Baseimage / deploy-quay" checks fail because I don't have the permissions to push there. Seems like there is nothing I can do against this.

Yes, I believe you're right. Think we had a case of that not long ago.

**Comment by rschwebel** [comment]
Could you re-trigger the tests and check if it works then?

**Comment by kzangeli** [comment]
> Could you re-trigger the tests and check if it works then?

Won't solve a thing.
But, no worries, I don't need that to work to accept the PR.
Just, give be a little bit of time :)
I have a list of things I need to fix asap.
I'll look into this PR as soon as I've put out all those fires.

**Comment by rschwebel** [comment]
Hold on, I found something to improve...

**Comment by rschwebel** [comment]
I've now pushed the fixed patch series. Please review.

**Review by kzangeli — APPROVED** [review]
LGTM
Thank you for contributing!!!

**Pull request merged**
